name: openbase-web

services:
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-6379}:6379

  db:
    image: pgvector/pgvector:pg14
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdata
    ports:
      - ${DB_PORT:-5432}:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT:-80}:80
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-http://web:8000}
      - FRONTEND_PROXY_TARGET=${FRONTEND_PROXY_TARGET:-http://host.docker.internal:8080}

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_PAT=${GH_PAT}
        - SKIP_APP_REQUIREMENTS=true
    ports:
      - ${WEB_DEBUG_PORT:-5678}:5678
      - ${WEB_PORT:-8000}:8000
    env_file:
      - .env
    volumes:
      - .:/app/web
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appdata
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    entrypoint: ["bash", "/app/web/scripts/dev-entrypoint.sh"]
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload ${RELOAD_FLAGS:-}

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_PAT=${GH_PAT}
        - SKIP_APP_REQUIREMENTS=true
    ports:
      - ${WORKER_DEBUG_PORT:-5679}:5678
    env_file:
      - .env
    volumes:
      - .:/app/web
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appdata
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    entrypoint: ["bash", "/app/web/scripts/dev-entrypoint.sh"]
    command: python -m debugpy --listen 0.0.0.0:5678 -m taskiq worker --log-level=DEBUG --reload ${RELOAD_FLAGS:-} config.taskiq_config:broker config.taskiq_tasks
