name: openbase-web

services:
  redis:
    image: redis
    ports:
      - 6381:6379

  db:
    image: pgvector/pgvector:pg14
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdata
    ports:
      - 5434:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 81:80
      - 444:443
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-http://host.docker.internal:8000}
      - FRONTEND_PROXY_TARGET=${FRONTEND_PROXY_TARGET:-http://host.docker.internal:8080}
